// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCKgWzFwfZO0QtfWuKTqDcbBdeY68_IHkg',
    appId: '1:12304981681:web:6af284dcaa3f50d9fd0c90',
    messagingSenderId: '12304981681',
    projectId: 'agrovigya-362d7',
    authDomain: 'agrovigya-362d7.firebaseapp.com',
    storageBucket: 'agrovigya-362d7.firebasestorage.app',
    measurementId: 'G-TVTSZ6T871',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCvf6lV5P0F5DCooWZaHPK9rD9jNO2JnF4',
    appId: '1:12304981681:android:d7345c78dcc1cb2cfd0c90',
    messagingSenderId: '12304981681',
    projectId: 'agrovigya-362d7',
    storageBucket: 'agrovigya-362d7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAY1uIaHLXwU7ToYrf3mCf7UmpxTNNEDUw',
    appId: '1:12304981681:ios:5ce1602dd9829b96fd0c90',
    messagingSenderId: '12304981681',
    projectId: 'agrovigya-362d7',
    storageBucket: 'agrovigya-362d7.firebasestorage.app',
    iosClientId: '12304981681-oagknoj5edd8h9d22ton18b4gcpk7nqf.apps.googleusercontent.com',
    iosBundleId: 'com.example.agro',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAY1uIaHLXwU7ToYrf3mCf7UmpxTNNEDUw',
    appId: '1:12304981681:ios:5ce1602dd9829b96fd0c90',
    messagingSenderId: '12304981681',
    projectId: 'agrovigya-362d7',
    storageBucket: 'agrovigya-362d7.firebasestorage.app',
    iosClientId: '12304981681-oagknoj5edd8h9d22ton18b4gcpk7nqf.apps.googleusercontent.com',
    iosBundleId: 'com.example.agro',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCKgWzFwfZO0QtfWuKTqDcbBdeY68_IHkg',
    appId: '1:12304981681:web:9d75875dcc86ae54fd0c90',
    messagingSenderId: '12304981681',
    projectId: 'agrovigya-362d7',
    authDomain: 'agrovigya-362d7.firebaseapp.com',
    storageBucket: 'agrovigya-362d7.firebasestorage.app',
    measurementId: 'G-G6NJYV7GQV',
  );
}
